export const AccordionOne = () => import('../../components/AccordionOne.vue' /* webpackChunkName: "components/accordion-one" */).then(c => wrapFunctional(c.default || c))
export const FunFact = () => import('../../components/FunFact.vue' /* webpackChunkName: "components/fun-fact" */).then(c => wrapFunctional(c.default || c))
export const InstagramPost = () => import('../../components/InstagramPost.vue' /* webpackChunkName: "components/instagram-post" */).then(c => wrapFunctional(c.default || c))
export const About = () => import('../../components/about-us-one/About.vue' /* webpackChunkName: "components/about" */).then(c => wrapFunctional(c.default || c))
export const AboutUsOneFunFact = () => import('../../components/about-us-one/FunFact.vue' /* webpackChunkName: "components/about-us-one-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const AboutUsOneInstructor = () => import('../../components/about-us-one/Instructor.vue' /* webpackChunkName: "components/about-us-one-instructor" */).then(c => wrapFunctional(c.default || c))
export const AboutUsOneWhyChoose = () => import('../../components/about-us-one/WhyChoose.vue' /* webpackChunkName: "components/about-us-one-why-choose" */).then(c => wrapFunctional(c.default || c))
export const AboutUsThreeContactInfo = () => import('../../components/about-us-three/ContactInfo.vue' /* webpackChunkName: "components/about-us-three-contact-info" */).then(c => wrapFunctional(c.default || c))
export const AboutUsThreeFunFact = () => import('../../components/about-us-three/FunFact.vue' /* webpackChunkName: "components/about-us-three-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const AboutUsThreeInstructor = () => import('../../components/about-us-three/Instructor.vue' /* webpackChunkName: "components/about-us-three-instructor" */).then(c => wrapFunctional(c.default || c))
export const AboutUsThreeTestimonial = () => import('../../components/about-us-three/Testimonial.vue' /* webpackChunkName: "components/about-us-three-testimonial" */).then(c => wrapFunctional(c.default || c))
export const AboutUsThreeWhyChoose = () => import('../../components/about-us-three/WhyChoose.vue' /* webpackChunkName: "components/about-us-three-why-choose" */).then(c => wrapFunctional(c.default || c))
export const BlogPostList = () => import('../../components/blog/BlogPostList.vue' /* webpackChunkName: "components/blog-post-list" */).then(c => wrapFunctional(c.default || c))
export const BlogPostOne = () => import('../../components/blog/BlogPostOne.vue' /* webpackChunkName: "components/blog-post-one" */).then(c => wrapFunctional(c.default || c))
export const BlogPostStandard = () => import('../../components/blog/BlogPostStandard.vue' /* webpackChunkName: "components/blog-post-standard" */).then(c => wrapFunctional(c.default || c))
export const BlogPostTwo = () => import('../../components/blog/BlogPostTwo.vue' /* webpackChunkName: "components/blog-post-two" */).then(c => wrapFunctional(c.default || c))
export const CommonBreadCrumbOne = () => import('../../components/common/BreadCrumbOne.vue' /* webpackChunkName: "components/common-bread-crumb-one" */).then(c => wrapFunctional(c.default || c))
export const CommonBreadCrumbThree = () => import('../../components/common/BreadCrumbThree.vue' /* webpackChunkName: "components/common-bread-crumb-three" */).then(c => wrapFunctional(c.default || c))
export const CommonBreadCrumbTwo = () => import('../../components/common/BreadCrumbTwo.vue' /* webpackChunkName: "components/common-bread-crumb-two" */).then(c => wrapFunctional(c.default || c))
export const CommonColorMode = () => import('../../components/common/ColorMode.vue' /* webpackChunkName: "components/common-color-mode" */).then(c => wrapFunctional(c.default || c))
export const CommonPaginationOne = () => import('../../components/common/PaginationOne.vue' /* webpackChunkName: "components/common-pagination-one" */).then(c => wrapFunctional(c.default || c))
export const CommonSectionTitle = () => import('../../components/common/SectionTitle.vue' /* webpackChunkName: "components/common-section-title" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeEight = () => import('../../components/course/CourseTypeEight.vue' /* webpackChunkName: "components/course-type-eight" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeFive = () => import('../../components/course/CourseTypeFive.vue' /* webpackChunkName: "components/course-type-five" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeFour = () => import('../../components/course/CourseTypeFour.vue' /* webpackChunkName: "components/course-type-four" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeOne = () => import('../../components/course/CourseTypeOne.vue' /* webpackChunkName: "components/course-type-one" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeSeven = () => import('../../components/course/CourseTypeSeven.vue' /* webpackChunkName: "components/course-type-seven" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeSix = () => import('../../components/course/CourseTypeSix.vue' /* webpackChunkName: "components/course-type-six" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeThree = () => import('../../components/course/CourseTypeThree.vue' /* webpackChunkName: "components/course-type-three" */).then(c => wrapFunctional(c.default || c))
export const CourseTypeTwo = () => import('../../components/course/CourseTypeTwo.vue' /* webpackChunkName: "components/course-type-two" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoFeatures = () => import('../../components/about-us-two/Features.vue' /* webpackChunkName: "components/about-us-two-features" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoFunFact = () => import('../../components/about-us-two/FunFact.vue' /* webpackChunkName: "components/about-us-two-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoInstructor = () => import('../../components/about-us-two/Instructor.vue' /* webpackChunkName: "components/about-us-two-instructor" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoLogo = () => import('../../components/about-us-two/Logo.vue' /* webpackChunkName: "components/about-us-two-logo" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoTestimonial = () => import('../../components/about-us-two/Testimonial.vue' /* webpackChunkName: "components/about-us-two-testimonial" */).then(c => wrapFunctional(c.default || c))
export const AboutUsTwoVideo = () => import('../../components/about-us-two/Video.vue' /* webpackChunkName: "components/about-us-two-video" */).then(c => wrapFunctional(c.default || c))
export const AnimationMouseMove = () => import('../../components/animation/MouseMove.vue' /* webpackChunkName: "components/animation-mouse-move" */).then(c => wrapFunctional(c.default || c))
export const CtaCTAOne = () => import('../../components/cta/CTAOne.vue' /* webpackChunkName: "components/cta-c-t-a-one" */).then(c => wrapFunctional(c.default || c))
export const CtaCTAOneAlter = () => import('../../components/cta/CTAOneAlter.vue' /* webpackChunkName: "components/cta-c-t-a-one-alter" */).then(c => wrapFunctional(c.default || c))
export const EventList = () => import('../../components/event/EventList.vue' /* webpackChunkName: "components/event-list" */).then(c => wrapFunctional(c.default || c))
export const EventOne = () => import('../../components/event/EventOne.vue' /* webpackChunkName: "components/event-one" */).then(c => wrapFunctional(c.default || c))
export const EventSectionOne = () => import('../../components/event/EventSectionOne.vue' /* webpackChunkName: "components/event-section-one" */).then(c => wrapFunctional(c.default || c))
export const EventTwo = () => import('../../components/event/EventTwo.vue' /* webpackChunkName: "components/event-two" */).then(c => wrapFunctional(c.default || c))
export const FooterKindergarten = () => import('../../components/footer/FooterKindergarten.vue' /* webpackChunkName: "components/footer-kindergarten" */).then(c => wrapFunctional(c.default || c))
export const FooterKitchen = () => import('../../components/footer/FooterKitchen.vue' /* webpackChunkName: "components/footer-kitchen" */).then(c => wrapFunctional(c.default || c))
export const FooterLanding = () => import('../../components/footer/FooterLanding.vue' /* webpackChunkName: "components/footer-landing" */).then(c => wrapFunctional(c.default || c))
export const FooterOne = () => import('../../components/footer/FooterOne.vue' /* webpackChunkName: "components/footer-one" */).then(c => wrapFunctional(c.default || c))
export const FooterThree = () => import('../../components/footer/FooterThree.vue' /* webpackChunkName: "components/footer-three" */).then(c => wrapFunctional(c.default || c))
export const FooterTwo = () => import('../../components/footer/FooterTwo.vue' /* webpackChunkName: "components/footer-two" */).then(c => wrapFunctional(c.default || c))
export const FooterYoga = () => import('../../components/footer/FooterYoga.vue' /* webpackChunkName: "components/footer-yoga" */).then(c => wrapFunctional(c.default || c))
export const FooterGoogleMapWithAPI = () => import('../../components/footer/GoogleMapWithAPI.vue' /* webpackChunkName: "components/footer-google-map-with-a-p-i" */).then(c => wrapFunctional(c.default || c))
export const FooterScrollToTop = () => import('../../components/footer/ScrollToTop.vue' /* webpackChunkName: "components/footer-scroll-to-top" */).then(c => wrapFunctional(c.default || c))
export const HeaderCategory = () => import('../../components/header/Category.vue' /* webpackChunkName: "components/header-category" */).then(c => wrapFunctional(c.default || c))
export const HeaderFour = () => import('../../components/header/HeaderFour.vue' /* webpackChunkName: "components/header-four" */).then(c => wrapFunctional(c.default || c))
export const HeaderLanding = () => import('../../components/header/HeaderLanding.vue' /* webpackChunkName: "components/header-landing" */).then(c => wrapFunctional(c.default || c))
export const HeaderOne = () => import('../../components/header/HeaderOne.vue' /* webpackChunkName: "components/header-one" */).then(c => wrapFunctional(c.default || c))
export const HeaderThree = () => import('../../components/header/HeaderThree.vue' /* webpackChunkName: "components/header-three" */).then(c => wrapFunctional(c.default || c))
export const HeaderTopOne = () => import('../../components/header/HeaderTopOne.vue' /* webpackChunkName: "components/header-top-one" */).then(c => wrapFunctional(c.default || c))
export const HeaderTopTwo = () => import('../../components/header/HeaderTopTwo.vue' /* webpackChunkName: "components/header-top-two" */).then(c => wrapFunctional(c.default || c))
export const HeaderTwo = () => import('../../components/header/HeaderTwo.vue' /* webpackChunkName: "components/header-two" */).then(c => wrapFunctional(c.default || c))
export const HeaderMobileMenu = () => import('../../components/header/MobileMenu.vue' /* webpackChunkName: "components/header-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const HeaderNavigation = () => import('../../components/header/Navigation.vue' /* webpackChunkName: "components/header-navigation" */).then(c => wrapFunctional(c.default || c))
export const HeaderOffCanvasMobileMenuOne = () => import('../../components/header/OffCanvasMobileMenuOne.vue' /* webpackChunkName: "components/header-off-canvas-mobile-menu-one" */).then(c => wrapFunctional(c.default || c))
export const HeaderOffCanvasMobileMenuTwo = () => import('../../components/header/OffCanvasMobileMenuTwo.vue' /* webpackChunkName: "components/header-off-canvas-mobile-menu-two" */).then(c => wrapFunctional(c.default || c))
export const HeaderSearchPopUp = () => import('../../components/header/SearchPopUp.vue' /* webpackChunkName: "components/header-search-pop-up" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningAbout = () => import('../../components/home-distant-learning/About.vue' /* webpackChunkName: "components/home-distant-learning-about" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningBanner = () => import('../../components/home-distant-learning/Banner.vue' /* webpackChunkName: "components/home-distant-learning-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningBlog = () => import('../../components/home-distant-learning/Blog.vue' /* webpackChunkName: "components/home-distant-learning-blog" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningCategories = () => import('../../components/home-distant-learning/Categories.vue' /* webpackChunkName: "components/home-distant-learning-categories" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningCourse = () => import('../../components/home-distant-learning/Course.vue' /* webpackChunkName: "components/home-distant-learning-course" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningFAQ = () => import('../../components/home-distant-learning/FAQ.vue' /* webpackChunkName: "components/home-distant-learning-f-a-q" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningFunFact = () => import('../../components/home-distant-learning/FunFact.vue' /* webpackChunkName: "components/home-distant-learning-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningLogo = () => import('../../components/home-distant-learning/Logo.vue' /* webpackChunkName: "components/home-distant-learning-logo" */).then(c => wrapFunctional(c.default || c))
export const HomeDistantLearningVideo = () => import('../../components/home-distant-learning/Video.vue' /* webpackChunkName: "components/home-distant-learning-video" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenAbout = () => import('../../components/home-kindergarten/About.vue' /* webpackChunkName: "components/home-kindergarten-about" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenActivities = () => import('../../components/home-kindergarten/Activities.vue' /* webpackChunkName: "components/home-kindergarten-activities" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenBanner = () => import('../../components/home-kindergarten/Banner.vue' /* webpackChunkName: "components/home-kindergarten-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenBlog = () => import('../../components/home-kindergarten/Blog.vue' /* webpackChunkName: "components/home-kindergarten-blog" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenCourse = () => import('../../components/home-kindergarten/Course.vue' /* webpackChunkName: "components/home-kindergarten-course" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenEvent = () => import('../../components/home-kindergarten/Event.vue' /* webpackChunkName: "components/home-kindergarten-event" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenFAQ = () => import('../../components/home-kindergarten/FAQ.vue' /* webpackChunkName: "components/home-kindergarten-f-a-q" */).then(c => wrapFunctional(c.default || c))
export const HomeKindergartenSubscriptionForm = () => import('../../components/home-kindergarten/SubscriptionForm.vue' /* webpackChunkName: "components/home-kindergarten-subscription-form" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachAbout = () => import('../../components/home-kitchen-coach/About.vue' /* webpackChunkName: "components/home-kitchen-coach-about" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachBanner = () => import('../../components/home-kitchen-coach/Banner.vue' /* webpackChunkName: "components/home-kitchen-coach-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachBlog = () => import('../../components/home-kitchen-coach/Blog.vue' /* webpackChunkName: "components/home-kitchen-coach-blog" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachCTA = () => import('../../components/home-kitchen-coach/CTA.vue' /* webpackChunkName: "components/home-kitchen-coach-c-t-a" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachCourse = () => import('../../components/home-kitchen-coach/Course.vue' /* webpackChunkName: "components/home-kitchen-coach-course" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachFAQ = () => import('../../components/home-kitchen-coach/FAQ.vue' /* webpackChunkName: "components/home-kitchen-coach-f-a-q" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachFeatures = () => import('../../components/home-kitchen-coach/Features.vue' /* webpackChunkName: "components/home-kitchen-coach-features" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachFunFact = () => import('../../components/home-kitchen-coach/FunFact.vue' /* webpackChunkName: "components/home-kitchen-coach-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachInstagram = () => import('../../components/home-kitchen-coach/Instagram.vue' /* webpackChunkName: "components/home-kitchen-coach-instagram" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachInstructor = () => import('../../components/home-kitchen-coach/Instructor.vue' /* webpackChunkName: "components/home-kitchen-coach-instructor" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachLogo = () => import('../../components/home-kitchen-coach/Logo.vue' /* webpackChunkName: "components/home-kitchen-coach-logo" */).then(c => wrapFunctional(c.default || c))
export const HomeKitchenCoachTestimonial = () => import('../../components/home-kitchen-coach/Testimonial.vue' /* webpackChunkName: "components/home-kitchen-coach-testimonial" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoBanner = () => import('../../components/home-landing-demo/Banner.vue' /* webpackChunkName: "components/home-landing-demo-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoCourseLayout = () => import('../../components/home-landing-demo/CourseLayout.vue' /* webpackChunkName: "components/home-landing-demo-course-layout" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoFeatures = () => import('../../components/home-landing-demo/Features.vue' /* webpackChunkName: "components/home-landing-demo-features" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoFunFact = () => import('../../components/home-landing-demo/FunFact.vue' /* webpackChunkName: "components/home-landing-demo-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeDemo = () => import('../../components/home-landing-demo/HomeDemo.vue' /* webpackChunkName: "components/home-demo" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoInnerPages = () => import('../../components/home-landing-demo/InnerPages.vue' /* webpackChunkName: "components/home-landing-demo-inner-pages" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoLearnWith = () => import('../../components/home-landing-demo/LearnWith.vue' /* webpackChunkName: "components/home-landing-demo-learn-with" */).then(c => wrapFunctional(c.default || c))
export const HomeLandingDemoShopLayout = () => import('../../components/home-landing-demo/ShopLayout.vue' /* webpackChunkName: "components/home-landing-demo-shop-layout" */).then(c => wrapFunctional(c.default || c))
export const HomeMainAbout = () => import('../../components/home-main/About.vue' /* webpackChunkName: "components/home-main-about" */).then(c => wrapFunctional(c.default || c))
export const HomeMainBanner = () => import('../../components/home-main/Banner.vue' /* webpackChunkName: "components/home-main-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeMainBlog = () => import('../../components/home-main/Blog.vue' /* webpackChunkName: "components/home-main-blog" */).then(c => wrapFunctional(c.default || c))
export const HomeMainCategories = () => import('../../components/home-main/Categories.vue' /* webpackChunkName: "components/home-main-categories" */).then(c => wrapFunctional(c.default || c))
export const HomeMainContactInfo = () => import('../../components/home-main/ContactInfo.vue' /* webpackChunkName: "components/home-main-contact-info" */).then(c => wrapFunctional(c.default || c))
export const HomeMainCourse = () => import('../../components/home-main/Course.vue' /* webpackChunkName: "components/home-main-course" */).then(c => wrapFunctional(c.default || c))
export const HomeMainFeatures = () => import('../../components/home-main/Features.vue' /* webpackChunkName: "components/home-main-features" */).then(c => wrapFunctional(c.default || c))
export const HomeMainFunFact = () => import('../../components/home-main/FunFact.vue' /* webpackChunkName: "components/home-main-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeMainInstructor = () => import('../../components/home-main/Instructor.vue' /* webpackChunkName: "components/home-main-instructor" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyBanner = () => import('../../components/home-online-academy/Banner.vue' /* webpackChunkName: "components/home-online-academy-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyBlog = () => import('../../components/home-online-academy/Blog.vue' /* webpackChunkName: "components/home-online-academy-blog" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyCategories = () => import('../../components/home-online-academy/Categories.vue' /* webpackChunkName: "components/home-online-academy-categories" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyContactInfo = () => import('../../components/home-online-academy/ContactInfo.vue' /* webpackChunkName: "components/home-online-academy-contact-info" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyCourse = () => import('../../components/home-online-academy/Course.vue' /* webpackChunkName: "components/home-online-academy-course" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyFAQ = () => import('../../components/home-online-academy/FAQ.vue' /* webpackChunkName: "components/home-online-academy-f-a-q" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyFunFact = () => import('../../components/home-online-academy/FunFact.vue' /* webpackChunkName: "components/home-online-academy-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeOnlineAcademyInstructor = () => import('../../components/home-online-academy/Instructor.vue' /* webpackChunkName: "components/home-online-academy-instructor" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityAbout = () => import('../../components/home-university/About.vue' /* webpackChunkName: "components/home-university-about" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityBanner = () => import('../../components/home-university/Banner.vue' /* webpackChunkName: "components/home-university-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityCampus = () => import('../../components/home-university/Campus.vue' /* webpackChunkName: "components/home-university-campus" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityContactInfo = () => import('../../components/home-university/ContactInfo.vue' /* webpackChunkName: "components/home-university-contact-info" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityCourse = () => import('../../components/home-university/Course.vue' /* webpackChunkName: "components/home-university-course" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityFeatures = () => import('../../components/home-university/Features.vue' /* webpackChunkName: "components/home-university-features" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityFunFact = () => import('../../components/home-university/FunFact.vue' /* webpackChunkName: "components/home-university-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeUniversityVideo = () => import('../../components/home-university/Video.vue' /* webpackChunkName: "components/home-university-video" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorAbout = () => import('../../components/home-yoga-instructor/About.vue' /* webpackChunkName: "components/home-yoga-instructor-about" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorBanner = () => import('../../components/home-yoga-instructor/Banner.vue' /* webpackChunkName: "components/home-yoga-instructor-banner" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorCourse = () => import('../../components/home-yoga-instructor/Course.vue' /* webpackChunkName: "components/home-yoga-instructor-course" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorFunFact = () => import('../../components/home-yoga-instructor/FunFact.vue' /* webpackChunkName: "components/home-yoga-instructor-fun-fact" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorInstagram = () => import('../../components/home-yoga-instructor/Instagram.vue' /* webpackChunkName: "components/home-yoga-instructor-instagram" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructor = () => import('../../components/home-yoga-instructor/Instructor.vue' /* webpackChunkName: "components/home-yoga-instructor" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorTestimonial = () => import('../../components/home-yoga-instructor/Testimonial.vue' /* webpackChunkName: "components/home-yoga-instructor-testimonial" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorVideo = () => import('../../components/home-yoga-instructor/Video.vue' /* webpackChunkName: "components/home-yoga-instructor-video" */).then(c => wrapFunctional(c.default || c))
export const HomeYogaInstructorWhyChoose = () => import('../../components/home-yoga-instructor/WhyChoose.vue' /* webpackChunkName: "components/home-yoga-instructor-why-choose" */).then(c => wrapFunctional(c.default || c))
export const InstructorFive = () => import('../../components/instructor/InstructorFive.vue' /* webpackChunkName: "components/instructor-five" */).then(c => wrapFunctional(c.default || c))
export const InstructorFour = () => import('../../components/instructor/InstructorFour.vue' /* webpackChunkName: "components/instructor-four" */).then(c => wrapFunctional(c.default || c))
export const InstructorOne = () => import('../../components/instructor/InstructorOne.vue' /* webpackChunkName: "components/instructor-one" */).then(c => wrapFunctional(c.default || c))
export const InstructorThree = () => import('../../components/instructor/InstructorThree.vue' /* webpackChunkName: "components/instructor-three" */).then(c => wrapFunctional(c.default || c))
export const InstructorTwo = () => import('../../components/instructor/InstructorTwo.vue' /* webpackChunkName: "components/instructor-two" */).then(c => wrapFunctional(c.default || c))
export const LogoOne = () => import('../../components/logo/LogoOne.vue' /* webpackChunkName: "components/logo-one" */).then(c => wrapFunctional(c.default || c))
export const LogoTwo = () => import('../../components/logo/LogoTwo.vue' /* webpackChunkName: "components/logo-two" */).then(c => wrapFunctional(c.default || c))
export const ProductOne = () => import('../../components/product/ProductOne.vue' /* webpackChunkName: "components/product-one" */).then(c => wrapFunctional(c.default || c))
export const SidebarBlogSidebarOne = () => import('../../components/sidebar/BlogSidebarOne.vue' /* webpackChunkName: "components/sidebar-blog-sidebar-one" */).then(c => wrapFunctional(c.default || c))
export const SidebarCourseSidebarOne = () => import('../../components/sidebar/CourseSidebarOne.vue' /* webpackChunkName: "components/sidebar-course-sidebar-one" */).then(c => wrapFunctional(c.default || c))
export const SidebarEventSidebar = () => import('../../components/sidebar/EventSidebar.vue' /* webpackChunkName: "components/sidebar-event-sidebar" */).then(c => wrapFunctional(c.default || c))
export const SidebarPageSidebarOne = () => import('../../components/sidebar/PageSidebarOne.vue' /* webpackChunkName: "components/sidebar-page-sidebar-one" */).then(c => wrapFunctional(c.default || c))
export const TestimonialOne = () => import('../../components/testimonial/TestimonialOne.vue' /* webpackChunkName: "components/testimonial-one" */).then(c => wrapFunctional(c.default || c))
export const TestimonialThree = () => import('../../components/testimonial/TestimonialThree.vue' /* webpackChunkName: "components/testimonial-three" */).then(c => wrapFunctional(c.default || c))
export const TestimonialTwo = () => import('../../components/testimonial/TestimonialTwo.vue' /* webpackChunkName: "components/testimonial-two" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
